### ISSUE TITLE
Content [Meta]

### ISSUE THREAD

**Issue by mherchel** [mherchel/fldc-issues#1]
**Global**
- [x] Site title
- [x] Header heading
- [x] Copyright in footer

**Sidebar**
- [x]  Update tweet header

**Menu** 
- [x] Remove schedule

**Front**
- [x]  Main heading
- [x]  Dates & Block info
- [x]  Remove featured Speakers
  - [x]  Put up placeholders
- [x]  Remove sponsors

**About Page**
- [x] Verify Content

**Location**
- [x] Verify Content

**Lodging**
- [x] Update with https://www.drupal.org/node/2628316

**News**
- [x] Remove old news articles
- [x] Create new one

**Speaker Info**
- [x] Verify Content

**Contact Us**
- [x] Verify still works!

**Sponsors**
- [x] Verify Content
- [x] Verify old sponsors removed

**Become a sponsor**
- [x] Update Content

**Attendees**
- [x] Remove menu item?

**After Party**
- [x] Update Content

**Community Day**
- [x] Remove menu item?

**Tourism**
- [x] Verify Content

**Twitter Contest**
- [x] Remove menu item?

**FAQ**
- [x] Update Content

**Comment by ThatGuyCND** [comment]
these should be brought to the organizing group:
- Removal of:
-- Attendees page (until we have attendees, maybe use this page to link back to 2016 EB event)
-- Community Day
-- Twitter Contest

**Comment by mherchel** [comment]
@ThatGuyCND Agree!

**Comment by mherchel** [comment]
Content updated and closing
